"""Art generation using Google Gemini Flash Image API (Nano Banana)."""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

STYLE_REFERENCES_DIR = Path(__file__).parent / "cli" / "assets" / "style_references"

ART_STYLE_PREFIX = (
    "Create a full-bleed illustration with NO text, NO words, NO letters, NO titles, "
    "NO border, NO frame, NO decorative edges. The image must fill the entire canvas "
    "edge to edge. "
    "Art style: naturalistic painterly illustration in the style of Spirit Island "
    "board game card art — rich colors, traditional media feel (watercolor/gouache/oil), "
    "lush natural environments, mystical atmosphere, detailed but not photorealistic. "
    "Subject: "
)


def _load_style_references(num_examples: int) -> list[Path]:
    """Load up to num_examples style reference images, sorted by name."""
    if not STYLE_REFERENCES_DIR.is_dir():
        return []
    refs = sorted(STYLE_REFERENCES_DIR.glob("example_*.png"))
    return refs[:num_examples]


def generate_art(
    prompt: str,
    output_path: Path,
    timeout: int = 300,
    num_examples: int = 0,
    references: list[Path] | None = None,
) -> tuple[Path, int]:
    """Generate art using Gemini Flash Image and save to output_path.

    Args:
        prompt: The image generation prompt.
        output_path: Where to save the generated image.
        timeout: Request timeout in seconds (default 300).
        num_examples: Number of style example images to attach (default 0).
        references: Additional custom reference image paths.

    Returns:
        Tuple of (output_path, total number of reference images used).
    """
    from google import genai
    from google.genai import types

    load_dotenv()
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        raise ValueError(
            "GOOGLE_API_KEY not found. Set it in your .env file."
        )

    client = genai.Client(
        api_key=api_key,
        http_options={"timeout": timeout * 1000},
    )

    # Build multimodal contents: style prefix + references + prompt
    full_prompt = ART_STYLE_PREFIX + prompt
    contents: list = []
    style_refs = _load_style_references(num_examples)
    custom_refs = references or []

    all_refs = style_refs + custom_refs
    if all_refs:
        contents.append(
            "Generate art in the same visual style as these reference images. "
            "Match the painterly quality, color palette, and artistic approach:"
        )
        for ref_path in all_refs:
            image_bytes = ref_path.read_bytes()
            mime = "image/jpeg" if ref_path.suffix.lower() in (".jpg", ".jpeg") else "image/png"
            contents.append(
                types.Part.from_bytes(data=image_bytes, mime_type=mime)
            )
        contents.append(f"Now generate the following, in that same art style:\n{full_prompt}")
    else:
        contents.append(full_prompt)

    response = client.models.generate_content(
        model="gemini-2.5-flash-image",
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["TEXT", "IMAGE"],
            image_config=types.ImageConfig(
                aspect_ratio="4:3",
            ),
        ),
    )

    # Find the image part in the response
    if not response.candidates:
        raise RuntimeError(
            "No candidates returned by the Gemini API. "
            "The prompt may have been blocked by safety filters."
        )

    for part in response.candidates[0].content.parts:
        if part.inline_data and part.inline_data.mime_type.startswith("image/"):
            output_path.write_bytes(part.inline_data.data)
            return output_path, len(all_refs)

    # No image found — show what we got back
    text_parts = [
        p.text for p in response.candidates[0].content.parts if p.text
    ]
    detail = f" Response text: {'; '.join(text_parts)}" if text_parts else ""
    raise RuntimeError(f"No image was generated by the Gemini API.{detail}")
